### ISSUE TITLE
Cannot successfully run with CARLA 0.9.13

### ISSUE THREAD

**Issue by chiehchiYang** [uoe-agents/IGP2#7]
Thanks for your great work.
I meet some errors when running " python scripts/run.py --map Town01 --carla"
1.
Traceback (most recent call last):
  File "scripts/run.py", line 69, in main
    result = run_carla_simulation(simulation, ego_agent, args, config)
  File "scripts/run.py", line 89, in run_carla_simulation
    tm.update(simulation)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/carlasim/traffic_manager.py", line 79, in update
    self.__spawn_agent(simulation)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/carlasim/traffic_manager.py", line 129, in __spawn_agent
    agent = carla.CarlaAgentWrapper(agent, vehicle)
AttributeError: module 'carla' has no attribute 'CarlaAgentWrapper'
----
I solve this error by change carla.CarlaAgentWrapper(agent, vehicle) --> to   CarlaAgentWrapper(agent, vehicle)

2. And then, there is another error that I have no idea how to deal with it. Could you please teach me how to solve it.

[MainThread:igp2.opendrive.map  ] [INFO  ]  Parsing map scenarios/maps/Town01.xodr.
/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
[MainThread:igp2.carlasim.carla_] [INFO  ]  Launching CARLA simulation (server=localhost, port=2000).
[MainThread:igp2.carlasim.carla_] [INFO  ]  Added agent 0 (actor 197).
[MainThread:igp2.agents.traffic_] [INFO  ]  Finding path for TrafficAgent ID 198
[MainThread:__main__            ] [ERROR ]  'NoneType' object is not iterable
Traceback (most recent call last):
  File "scripts/run.py", line 69, in main
    result = run_carla_simulation(simulation, ego_agent, args, config)
  File "scripts/run.py", line 89, in run_carla_simulation
    tm.update(simulation)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/carlasim/traffic_manager.py", line 79, in update
    self.__spawn_agent(simulation)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/carlasim/traffic_manager.py", line 131, in __spawn_agent
    self.__find_destination(agent, initial_state)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/carlasim/traffic_manager.py", line 145, in __find_destination
    agent.set_destination(Observation({agent.agent_id: state}, self.__scenario_map), goal)
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/agents/traffic_agent.py", line 45, in set_destination
    _, actions = self._astar.search(self.agent_id,
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/recognition/astar.py", line 113, in search
    for ma_args in macro_action.get_possible_args(frame[agent_id], scenario_map, goal):
  File "/home/chiehchiyang/miniconda3/envs/igp/lib/python3.8/site-packages/igp2/planlibrary/macro_action.py", line 703, in get_possible_args
    connecting_lanes = [suc for suc in current_lane.link.predecessor[0].link.successor
TypeError: 'NoneType' object is not iterable

**Comment by CurryChen77** [comment]
Having the same issue, any updates?

**Comment by chiehchiYang** [comment]
nope, just give up this repo
